on: 
  push:
    branches:
      - master

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Healthcheck
        uses: jtalk/url-health-check-action@v1.5
        with: https://helsinkicourse.herokuapp.com/
